name: webldraw
version: 0.1.0
author: Sebastian Wahl
description: WebGL-based LDraw viewer
homepage: https://github.com/spillerrec/WebLDraw/
dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  lzma: any
  vector_math: any
