name: webldraw
version: 0.1.0
author: Sebastian Wahl
description: WebGL-based LDraw viewer
homepage: https://github.com/spillerrec/WebLDraw/
dependencies:
  browser: any
  lzma: any
  vector_math: any
